/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_londatiga_android_bluebamboo_SerialPort */

#ifndef _Included_net_londatiga_android_bluebamboo_SerialPort
#define _Included_net_londatiga_android_bluebamboo_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_londatiga_android_bluebamboo_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_net_londatiga_android_bluebamboo_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     net_londatiga_android_bluebamboo_SerialPort
 * Method:    write
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_net_londatiga_android_bluebamboo_SerialPort_write
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     net_londatiga_android_bluebamboo_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_londatiga_android_bluebamboo_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
